FROM registry.access.redhat.com/ubi8/openjdk-21:1.20

USER 0:0

COPY --chown=0:0 CBOMkit-action.jar /cbombit-action/CBOMkit-action.jar
COPY --chown=0:0 src/main/resources/java/scan/*.jar /cbombit-action//java/scan/

RUN ls -l /
RUN ls -l /cbomkit-action 

ENV LANGUAGE='en_US:en'
ENV CBOMKIT_JAVA_JAR_DIR="/cbombit-action/java/scan"

CMD ["java","-Xmx16g","-jar","/cbomkit-action/CBOMkit-action.jar"]
